import { FormEvent, useCallback, useEffect, useState } from 'react';
import type { KitchenSnapshot } from '../domain/types';
import { actOnCase, createIncident, fetchBackupEvidence, fetchCases, fetchCheckpoints, fetchIncidents, fetchSnapshots, operationsApiBase, publishSnapshot, recordBackup, recordRestoreDrill, transitionIncident, type BackupEvidence, type ConfigurationSnapshot, type EdgeCheckpoint, type OperationalIncident, type ReconciliationCase } from '../domain/coreOperations';
import type { MessageKey } from '../i18n/messages';

interface Props { snapshot:KitchenSnapshot; t:(key:MessageKey,replacements?:Record<string,string|number>)=>string }
const api=operationsApiBase((import.meta.env.VITE_CORE_URL as string|undefined)?.trim());
const emptyEvidence:BackupEvidence={backups:[],restoreDrills:[]};

function OperationsControlLegacy({snapshot,t}:Props){
  const [snapshots,setSnapshots]=useState<ConfigurationSnapshot[]>([]);const [checkpoints,setCheckpoints]=useState<EdgeCheckpoint[]>([]);const [cases,setCases]=useState<ReconciliationCase[]>([]);const [incidents,setIncidents]=useState<OperationalIncident[]>([]);const [evidence,setEvidence]=useState<BackupEvidence>(emptyEvidence);const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const load=useCallback(async()=>{if(!api){setError(t('operations.notConfigured'));return}try{const [nextSnapshots,nextCheckpoints,nextCases,nextIncidents,nextEvidence]=await Promise.all([fetchSnapshots(api,snapshot.organizationId,snapshot.outletId),fetchCheckpoints(api,snapshot.organizationId,snapshot.outletId),fetchCases(api,snapshot.organizationId,snapshot.outletId),fetchIncidents(api,snapshot.organizationId,snapshot.outletId),fetchBackupEvidence(api,snapshot.organizationId)]);setSnapshots(nextSnapshots);setCheckpoints(nextCheckpoints);setCases(nextCases);setIncidents(nextIncidents);setEvidence(nextEvidence);setError('')}catch{setError(t('operations.unavailable'))}},[snapshot.organizationId,snapshot.outletId,t]);useEffect(()=>{void load()},[load]);
  const run=async(name:string,action:()=>Promise<unknown>)=>{if(!api)return;setBusy(name);setError('');try{await action();await load()}catch{setError(t('operations.actionFailed'))}finally{setBusy('')}};
  const report=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const title=String(data.get('title')??'').trim();const severity=String(data.get('severity')??'medium');if(!title||!api)return;await run('incident',()=>createIncident(api,snapshot.organizationId,snapshot.outletId,title,severity));event.currentTarget.reset()};
  const backup=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const reference=String(data.get('reference')??'').trim();const checksum=String(data.get('checksum')??'').trim().toLowerCase();const size=Number(data.get('size'));if(!reference||!/^[0-9a-f]{64}$/.test(checksum)||size<1||!api)return;await run('backup',()=>recordBackup(api,snapshot.organizationId,snapshot.outletId,reference,checksum,size));event.currentTarget.reset()};
  const unresolved=cases.filter(value=>value.status==='open'||value.status==='in_progress');const active=incidents.filter(value=>value.status!=='resolved');const degraded=checkpoints.filter(value=>value.degraded);
  return <section className="operations-page"><header className="page-heading"><div><span className="eyebrow">{t('operations.eyebrow')}</span><h1>{t('operations.title')}</h1><p>{t('operations.subtitle')}</p></div><button className="planning-generate" disabled={Boolean(busy)||!api} onClick={()=>void run('snapshot',()=>publishSnapshot(api!,snapshot.organizationId,snapshot.outletId,{schemaVersion:1,outletId:snapshot.outletId,publishedFrom:'manager-dashboard',kitchen:{orders:snapshot.orders.length,tickets:(snapshot.tickets??[]).length}}))}>{busy==='snapshot'?t('inventory.saving'):t('operations.publish')}</button></header>{error&&<p className="inventory-alert" role="alert">{error}</p>}
    <div className="operations-metrics"><strong>{unresolved.length}<small>{t('operations.cases')}</small></strong><strong className={degraded.length?'danger':''}>{degraded.length}<small>{t('operations.degraded')}</small></strong><strong>{active.length}<small>{t('operations.incidents')}</small></strong><strong>{snapshots[0]?.sequence??0}<small>{t('operations.snapshot')}</small></strong><strong>{evidence.backups.length}<small>{t('operations.backups')}</small></strong></div>
    <div className="operations-grid"><article className="operations-card span-two"><div className="section-title"><div><h2>{t('operations.reviewTitle')}</h2><p>{t('operations.reviewHelp')}</p></div></div>{unresolved.length?unresolved.map(value=><div className="operations-row" key={value.id}><div><span className={`severity ${value.severity}`}>{value.severity}</span><b>{value.title}</b><small>{value.sourceType} · v{value.version}</small></div><div><button disabled={Boolean(busy)} onClick={()=>void run(value.id,()=>actOnCase(api!,snapshot.organizationId,snapshot.outletId,value,'retry'))}>{t('operations.retry')}</button><button className="primary" disabled={Boolean(busy)} onClick={()=>void run(value.id,()=>actOnCase(api!,snapshot.organizationId,snapshot.outletId,value,'resolve'))}>{t('operations.resolve')}</button></div></div>):<p className="empty-production">{t('operations.noCases')}</p>}</article>
      <article className="operations-card"><h2>{t('operations.edgeTitle')}</h2>{checkpoints.length?checkpoints.map(value=><div className="checkpoint" key={value.edgeId}><span className={value.degraded?'status-dot danger':'status-dot'} /><div><b>{value.edgeId.slice(0,8)}</b><small>{value.degraded?(value.lastProblemCode??t('operations.degraded')):t('operations.healthy')} · v{value.version}</small></div></div>):<p className="empty-production">{t('operations.noEdges')}</p>}</article>
      <article className="operations-card"><h2>{t('operations.snapshotTitle')}</h2>{snapshots[0]?<div className="signature-proof"><b>#{snapshots[0].sequence} · {snapshots[0].algorithm}</b><code>{snapshots[0].contentSha256.slice(0,24)}…</code><small>{new Date(snapshots[0].signedAt).toLocaleString()}</small></div>:<p className="empty-production">{t('operations.noSnapshot')}</p>}</article>
      <article className="operations-card span-two"><h2>{t('operations.incidentTitle')}</h2><form className="operations-form" onSubmit={event=>void report(event)}><input name="title" required maxLength={160} placeholder={t('operations.incidentPlaceholder')} /><select name="severity" defaultValue="medium"><option value="low">{t('operations.severity.low')}</option><option value="medium">{t('operations.severity.medium')}</option><option value="high">{t('operations.severity.high')}</option><option value="critical">{t('operations.severity.critical')}</option></select><button disabled={Boolean(busy)}>{t('operations.report')}</button></form>{active.map(value=><div className="operations-row" key={value.id}><div><span className={`severity ${value.severity}`}>{t(`operations.severity.${value.severity}` as MessageKey)}</span><b>{value.title}</b><small>{value.status} · v{value.version}</small></div><div>{value.status==='open'&&<button onClick={()=>void run(value.id,()=>transitionIncident(api!,snapshot.organizationId,snapshot.outletId,value,'monitoring'))}>{t('operations.monitor')}</button>}<button className="primary" onClick={()=>void run(value.id,()=>transitionIncident(api!,snapshot.organizationId,snapshot.outletId,value,'resolved'))}>{t('operations.resolve')}</button></div></div>)}</article>
      <article className="operations-card span-two"><h2>{t('operations.backupTitle')}</h2><form className="operations-form backup-form" onSubmit={event=>void backup(event)}><input name="reference" required maxLength={300} placeholder={t('operations.backupPlaceholder')} /><input name="checksum" required pattern="[0-9a-fA-F]{64}" placeholder={t('operations.checksumPlaceholder')} /><input name="size" required type="number" min="1" placeholder={t('operations.sizePlaceholder')} /><button disabled={Boolean(busy)}>{t('operations.recordBackup')}</button></form>{evidence.backups.slice(0,4).map(value=><div className="operations-row" key={value.id}><div><b>{value.storageReference}</b><small>{value.backupType} · {value.sizeBytes} B · {value.verified?t('operations.verified'):t('operations.unverified')}</small></div><button disabled={Boolean(busy)||evidence.restoreDrills.some(drill=>drill.backupManifestId===value.id)} onClick={()=>void run(value.id,()=>recordRestoreDrill(api!,snapshot.organizationId,snapshot.outletId,value))}>{t('operations.recordDrill')}</button></div>)}</article>
    </div></section>
}

export function OperationsControl({snapshot,t}:Props){
  const [focus,setFocus]=useState<'reconcile'|'edge'|'incident'|'recovery'>('reconcile');
  return <div className="operations-shell" data-focus={focus}><nav className="operations-focus" aria-label={t('operations.focusLabel')}>{(['reconcile','edge','incident','recovery'] as const).map(value=><button key={value} type="button" className={focus===value?'active':''} aria-pressed={focus===value} onClick={()=>setFocus(value)}>{t(`operations.focus.${value}` as MessageKey)}</button>)}</nav><OperationsControlLegacy snapshot={snapshot} t={t}/></div>;
}
