import { ChangeEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { fetchOrderImports, fetchPlanningRuns, generatePlanningRun, importOrderCSV, planningApiBase, type OrderImport, type PlanningRecommendation, type PlanningRun } from '../domain/corePlanning';
import type { KitchenSnapshot } from '../domain/types';
import type { MessageKey } from '../i18n/messages';

const api=planningApiBase((import.meta.env.VITE_CORE_URL as string|undefined)?.trim());
export function PlanningHub({snapshot,t}:{snapshot:KitchenSnapshot;t:(key:MessageKey,replacements?:Record<string,string|number>)=>string}){
  const [imports,setImports]=useState<OrderImport[]>([]);const [runs,setRuns]=useState<PlanningRun[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string>();const [selected,setSelected]=useState<OrderImport>();const [focus,setFocus]=useState<'imports'|'forecast'|'prep'|'stockouts'>('forecast');
  const load=useCallback(async()=>{if(!api){setError(t('planning.notConfigured'));return}try{const[nextImports,nextRuns]=await Promise.all([fetchOrderImports(api,snapshot.organizationId,snapshot.outletId),fetchPlanningRuns(api,snapshot.organizationId,snapshot.outletId)]);setImports(nextImports);setRuns(nextRuns);setSelected(current=>current??nextImports[0]);setError(undefined)}catch{setError(t('planning.unavailable'))}},[snapshot.organizationId,snapshot.outletId,t]);useEffect(()=>{void load()},[load]);
  const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file||!api)return;setBusy(true);setError(undefined);try{const result=await importOrderCSV(api,snapshot.organizationId,snapshot.outletId,file.name,await file.text());setSelected(result);await load()}catch(value){setError(value instanceof Error?value.message:t('planning.importFailed'))}finally{setBusy(false)}};
  const generate=async()=>{if(!api)return;setBusy(true);setError(undefined);try{await generatePlanningRun(api,snapshot.organizationId,snapshot.outletId);await load()}catch{setError(t('planning.generateFailed'))}finally{setBusy(false)}};
  const latest=runs[0];const groups=useMemo(()=>({forecast:latest?.recommendations.filter(value=>value.type==='demand_forecast')??[],prep:latest?.recommendations.filter(value=>value.type==='prep_suggestion')??[],warnings:latest?.recommendations.filter(value=>value.type==='stockout_warning')??[]}),[latest]);
  const recommendation=(value:PlanningRecommendation)=><article className={`recommendation ${value.type}`} key={value.id}><div><strong>{value.menuItemName??value.ingredientName}</strong><p>{value.explanation}</p></div><span>{Math.round(value.confidence*100)}%</span></article>;
  return <section className="planning-page"><header className="page-heading"><div><span className="eyebrow">{t('planning.eyebrow')}</span><h1>{t('planning.title')}</h1><p>{t('planning.subtitle')}</p></div><button className="planning-generate" disabled={busy} onClick={()=>void generate()}>{busy?t('inventory.saving'):t('planning.generate')}</button></header>{error&&<p className="inventory-alert" role="alert">{error}</p>}<nav className="planning-focus" aria-label={t('planning.focusLabel')}>{(['imports','forecast','prep','stockouts'] as const).map(value=><button key={value} type="button" className={focus===value?'active':''} aria-pressed={focus===value} onClick={()=>setFocus(value)}>{t(`planning.focus.${value}` as MessageKey)}</button>)}</nav><div className="planning-grid" data-focus={focus}><article className="import-panel" data-area="imports"><div className="section-title"><div><h2>{t('planning.importTitle')}</h2><p>{t('planning.importHelp')}</p></div><label className="csv-upload">{busy?t('inventory.saving'):t('planning.chooseCsv')}<input type="file" accept=".csv,text/csv" onChange={event=>void upload(event)}/></label></div><code>externalRef,placedAt,orderType,itemCode,quantity</code><div className="import-history">{imports.map(value=><button key={value.id} className={selected?.id===value.id?'active':''} onClick={()=>setSelected(value)}><span>{value.fileName}</span><small>{t('planning.importScore',{accepted:value.acceptedRows,rejected:value.rejectedRows})}</small></button>)}</div>{selected&&<div className="reconciliation"><div className="reconciliation-metrics"><strong>{selected.acceptedRows}<small>{t('planning.accepted')}</small></strong><strong className={selected.rejectedRows?'has-errors':''}>{selected.rejectedRows}<small>{t('planning.rejected')}</small></strong></div>{selected.rows.filter(row=>row.status==='rejected').map(row=><p key={row.id}><b>{t('planning.row',{row:row.rowNumber})}</b> {row.errorMessage}</p>)}</div>}</article><div className="intelligence-panel" data-area="forecast prep stockouts"><div className="intelligence-heading"><div><h2>{t('planning.observeTitle')}</h2><p>{latest?t('planning.generatedAt',{date:new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(latest.generatedAt))}):t('planning.noRun')}</p></div>{latest&&<span>{t('planning.observeOnly')}</span>}</div><section data-area="forecast"><h3>{t('planning.forecasts')}</h3>{groups.forecast.map(recommendation)}{!groups.forecast.length&&<p className="empty-production">{t('planning.noEvidence')}</p>}</section><section data-area="prep"><h3>{t('planning.prepSuggestions')}</h3>{groups.prep.map(recommendation)}</section><section data-area="stockouts"><h3>{t('planning.stockoutWarnings')}</h3>{groups.warnings.map(recommendation)}{latest&&!groups.warnings.length&&<p className="planning-clear">{t('planning.noWarnings')}</p>}</section></div></div></section>;
}
