-- SPDX-License-Identifier: AGPL-3.0-only
BEGIN;
CREATE TABLE guest_profiles(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,full_name text NOT NULL,phone text NOT NULL DEFAULT '',email text NOT NULL DEFAULT '',locale text NOT NULL DEFAULT 'en-IN',dietary_labels text[] NOT NULL DEFAULT '{}',notes text NOT NULL DEFAULT '',marketing_consent boolean NOT NULL DEFAULT false,consent_updated_at timestamptz,version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE UNIQUE INDEX guest_profiles_phone_unique ON guest_profiles(tenant_id,phone) WHERE phone<>'';
CREATE UNIQUE INDEX guest_profiles_email_unique ON guest_profiles(tenant_id,lower(email)) WHERE email<>'';
CREATE TABLE guest_consent_events(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,guest_id uuid NOT NULL,purpose text NOT NULL CHECK(purpose IN('marketing')),granted boolean NOT NULL,source text NOT NULL,occurred_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,operation_id),FOREIGN KEY(tenant_id,guest_id) REFERENCES guest_profiles(tenant_id,id));
CREATE TABLE reservations(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,guest_id uuid,guest_name text NOT NULL,phone text NOT NULL DEFAULT '',party_size integer NOT NULL CHECK(party_size>0),scheduled_for timestamptz NOT NULL,duration_minutes integer NOT NULL DEFAULT 90 CHECK(duration_minutes BETWEEN 15 AND 720),status text NOT NULL CHECK(status IN('booked','waiting','seated','completed','cancelled','no_show')),source text NOT NULL DEFAULT 'staff',notes text NOT NULL DEFAULT '',version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,outlet_id) REFERENCES outlets(tenant_id,id),FOREIGN KEY(tenant_id,guest_id) REFERENCES guest_profiles(tenant_id,id));
CREATE INDEX reservations_service_queue ON reservations(tenant_id,outlet_id,status,scheduled_for,id);
CREATE TABLE promotions(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,code text NOT NULL,name text NOT NULL,discount_type text NOT NULL CHECK(discount_type IN('percentage','fixed')),discount_value integer NOT NULL CHECK(discount_value>0),min_order_minor bigint NOT NULL DEFAULT 0,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL CHECK(ends_at>starts_at),redemption_limit integer,redemption_count integer NOT NULL DEFAULT 0,active boolean NOT NULL DEFAULT true,version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,outlet_id,code),FOREIGN KEY(tenant_id,outlet_id) REFERENCES outlets(tenant_id,id));
CREATE TABLE promotion_redemptions(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,promotion_id uuid NOT NULL,guest_id uuid,order_id uuid,basket_minor bigint NOT NULL,discount_minor bigint NOT NULL,occurred_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,operation_id),FOREIGN KEY(tenant_id,promotion_id) REFERENCES promotions(tenant_id,id),FOREIGN KEY(tenant_id,guest_id) REFERENCES guest_profiles(tenant_id,id),FOREIGN KEY(tenant_id,outlet_id,order_id) REFERENCES orders(tenant_id,outlet_id,id));
CREATE TABLE loyalty_accounts(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,guest_id uuid NOT NULL,points_balance bigint NOT NULL DEFAULT 0 CHECK(points_balance>=0),lifetime_earned bigint NOT NULL DEFAULT 0,version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,guest_id),FOREIGN KEY(tenant_id,guest_id) REFERENCES guest_profiles(tenant_id,id));
CREATE TABLE loyalty_events(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,account_id uuid NOT NULL,event_type text NOT NULL CHECK(event_type IN('earn','redeem','adjustment','expiry')),points_delta bigint NOT NULL CHECK(points_delta<>0),reason text NOT NULL,order_id uuid,occurred_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,operation_id),FOREIGN KEY(tenant_id,account_id) REFERENCES loyalty_accounts(tenant_id,id));
ALTER TABLE cash_events DROP CONSTRAINT cash_events_event_type_check;
ALTER TABLE cash_events ADD CONSTRAINT cash_events_event_type_check CHECK(event_type IN('opening_float','cash_sale','cash_refund','cash_in','cash_out','closing_count'));
CREATE TRIGGER guest_consent_events_immutable BEFORE UPDATE OR DELETE ON guest_consent_events FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();
CREATE TRIGGER promotion_redemptions_immutable BEFORE UPDATE OR DELETE ON promotion_redemptions FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();
CREATE TRIGGER loyalty_events_immutable BEFORE UPDATE OR DELETE ON loyalty_events FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['guest_profiles','guest_consent_events','reservations','promotions','promotion_redemptions','loyalty_accounts','loyalty_events'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY %I ON %I USING (tenant_id=feastcloud.current_tenant_id()) WITH CHECK (tenant_id=feastcloud.current_tenant_id())',n||'_isolation',n);END LOOP;END $$;
COMMIT;
