-- SPDX-License-Identifier: AGPL-3.0-only
BEGIN;
CREATE TABLE menu_item_availability(tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,menu_item_id uuid NOT NULL,available boolean NOT NULL,reason text NOT NULL DEFAULT '',version bigint NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL,PRIMARY KEY(tenant_id,outlet_id,menu_item_id),FOREIGN KEY(tenant_id,outlet_id) REFERENCES outlets(tenant_id,id),FOREIGN KEY(tenant_id,menu_item_id) REFERENCES menu_items(tenant_id,id));
CREATE TABLE menu_availability_events(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,menu_item_id uuid NOT NULL,available boolean NOT NULL,reason text NOT NULL,actor_id text NOT NULL,occurred_at timestamptz NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,operation_id),FOREIGN KEY(tenant_id,outlet_id,menu_item_id) REFERENCES menu_item_availability(tenant_id,outlet_id,menu_item_id));
CREATE TABLE dining_tables(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,label text NOT NULL,section text NOT NULL DEFAULT '',capacity integer NOT NULL CHECK(capacity>0),status text NOT NULL CHECK(status IN('available','occupied','cleaning','disabled')),version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,outlet_id,label),FOREIGN KEY(tenant_id,outlet_id) REFERENCES outlets(tenant_id,id));
CREATE TABLE dining_sessions(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,table_id uuid NOT NULL,status text NOT NULL CHECK(status IN('open','closed','cancelled')),guest_count integer NOT NULL CHECK(guest_count>0),guest_name text NOT NULL DEFAULT '',opened_at timestamptz NOT NULL,closed_at timestamptz,version bigint NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,table_id) REFERENCES dining_tables(tenant_id,id));
CREATE UNIQUE INDEX dining_sessions_one_open ON dining_sessions(tenant_id,table_id) WHERE status='open';
CREATE TABLE cash_shifts(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,register_label text NOT NULL,status text NOT NULL CHECK(status IN('open','closed')),opening_float_minor bigint NOT NULL CHECK(opening_float_minor>=0),expected_cash_minor bigint NOT NULL,closing_count_minor bigint,variance_minor bigint,opened_at timestamptz NOT NULL,closed_at timestamptz,actor_id text NOT NULL,version bigint NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,outlet_id) REFERENCES outlets(tenant_id,id));
CREATE UNIQUE INDEX cash_shifts_one_open ON cash_shifts(tenant_id,outlet_id,register_label) WHERE status='open';
CREATE TABLE cash_events(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,cash_shift_id uuid NOT NULL,event_type text NOT NULL CHECK(event_type IN('opening_float','cash_sale','cash_in','cash_out','closing_count')),amount_minor bigint NOT NULL,reason text NOT NULL DEFAULT '',occurred_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,operation_id),FOREIGN KEY(tenant_id,cash_shift_id) REFERENCES cash_shifts(tenant_id,id));
CREATE TABLE tenders(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,order_id uuid NOT NULL,cash_shift_id uuid,tender_type text NOT NULL CHECK(tender_type IN('cash','upi','card_terminal','external')),amount_minor bigint NOT NULL CHECK(amount_minor>0),currency char(3) NOT NULL,provider_reference text NOT NULL DEFAULT '',status text NOT NULL CHECK(status IN('captured','reversed')),reverses_tender_id uuid,occurred_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,operation_id),FOREIGN KEY(tenant_id,outlet_id,order_id) REFERENCES orders(tenant_id,outlet_id,id),FOREIGN KEY(tenant_id,cash_shift_id) REFERENCES cash_shifts(tenant_id,id),FOREIGN KEY(tenant_id,reverses_tender_id) REFERENCES tenders(tenant_id,id),CHECK((status='reversed')=(reverses_tender_id IS NOT NULL)));
CREATE TABLE fiscal_receipts(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,order_id uuid NOT NULL,receipt_number text NOT NULL,currency char(3) NOT NULL,subtotal_minor bigint NOT NULL,discount_minor bigint NOT NULL,tax_minor bigint NOT NULL,service_charge_minor bigint NOT NULL,total_minor bigint NOT NULL,tax_snapshot jsonb NOT NULL,issued_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,outlet_id,receipt_number),UNIQUE(tenant_id,order_id),FOREIGN KEY(tenant_id,outlet_id,order_id) REFERENCES orders(tenant_id,outlet_id,id));
CREATE TABLE tender_settlements(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,outlet_id uuid NOT NULL,business_date date NOT NULL,tender_type text NOT NULL,gross_minor bigint NOT NULL,reversed_minor bigint NOT NULL,net_minor bigint NOT NULL,transaction_count integer NOT NULL,generated_at timestamptz NOT NULL,actor_id text NOT NULL,operation_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,outlet_id,business_date,tender_type),FOREIGN KEY(tenant_id,outlet_id) REFERENCES outlets(tenant_id,id));
CREATE TRIGGER menu_availability_events_immutable BEFORE UPDATE OR DELETE ON menu_availability_events FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();CREATE TRIGGER cash_events_immutable BEFORE UPDATE OR DELETE ON cash_events FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();CREATE TRIGGER tenders_immutable BEFORE UPDATE OR DELETE ON tenders FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();CREATE TRIGGER fiscal_receipts_immutable BEFORE UPDATE OR DELETE ON fiscal_receipts FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();CREATE TRIGGER tender_settlements_immutable BEFORE UPDATE OR DELETE ON tender_settlements FOR EACH ROW EXECUTE FUNCTION feastcloud.reject_immutable_change();
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['menu_item_availability','menu_availability_events','dining_tables','dining_sessions','cash_shifts','cash_events','tenders','fiscal_receipts','tender_settlements'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY %I ON %I USING (tenant_id=feastcloud.current_tenant_id()) WITH CHECK (tenant_id=feastcloud.current_tenant_id())',n||'_isolation',n);END LOOP;END $$;
COMMIT;
