import { createUuidV7, getDeviceId } from './kitchen';
import { coreApiBase } from './coreInventory';

export interface ImportRowResult {id:string;rowNumber:number;externalRef:string;status:'accepted'|'rejected';errorCode?:string;errorMessage?:string;orderId?:string;rawData:Record<string,unknown>}
export interface OrderImport {id:string;fileName:string;fileSha256:string;totalRows:number;acceptedRows:number;rejectedRows:number;status:string;importedAt:string;rows:ImportRowResult[]}
export interface PlanningRecommendation {id:string;type:'demand_forecast'|'prep_suggestion'|'stockout_warning';menuItemName?:string;ingredientName?:string;unitSymbol?:string;forecastQuantity:number;requiredQuantityBase:number;availableQuantityBase:number;confidence:number;explanation:string;evidence:Record<string,unknown>}
export interface PlanningRun {id:string;horizonStart:string;horizonEnd:string;modelVersion:string;status:'observed';evidenceFrom:string;evidenceTo:string;generatedAt:string;recommendations:PlanningRecommendation[]}
export interface ParsedCSVRow {id:string;rowNumber:number;externalRef:string;placedAt:string;orderType:string;itemCode:string;quantity:number;rawData:Record<string,unknown>}

function auth(tenantId:string):{actorId:string;headers:Record<string,string>}{const token=sessionStorage.getItem('feastcloud.oidc-access-token');if(token)return{actorId:'manager-dashboard',headers:{Authorization:`Bearer ${token}`}};return{actorId:'manager-dashboard',headers:{'X-FeastCloud-Tenant-ID':tenantId,'X-FeastCloud-Actor-ID':'manager-dashboard'}}}
async function mutate<T>(api:string,path:string,tenantId:string,outletId:string,payload:Record<string,unknown>):Promise<T>{const id=createUuidV7();const context=auth(tenantId);const envelope={id,tenantId,outletId,deviceId:getDeviceId(),actorId:context.actorId,occurredAt:new Date().toISOString(),source:'feastcloud.web',sourceId:id,schemaVersion:'1.0',idempotencyKey:id,payload};const response=await fetch(`${api}${path}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':id,...context.headers},body:JSON.stringify(envelope)});if(!response.ok)throw new Error(`${path} returned ${response.status}`);const body=await response.json() as {data?:T};if(!body.data)throw new Error('Response is invalid');return body.data}
async function list<T>(api:string,path:string,tenantId:string,outletId:string):Promise<T[]>{const response=await fetch(`${api}${path}?outletId=${encodeURIComponent(outletId)}&limit=50`,{headers:{Accept:'application/json',...auth(tenantId).headers},cache:'no-store'});if(!response.ok)throw new Error(`${path} returned ${response.status}`);const body=await response.json() as {data?:unknown};if(!Array.isArray(body.data))throw new Error('Response is invalid');return body.data as T[]}

function parseLine(line:string):string[]{const values:string[]=[];let value='';let quoted=false;for(let index=0;index<line.length;index++){const char=line[index];if(char==='"'){if(quoted&&line[index+1]==='"'){value+='"';index++}else quoted=!quoted}else if(char===','&&!quoted){values.push(value.trim());value=''}else value+=char}if(quoted)throw new Error('Unclosed quoted value');values.push(value.trim());return values}
export function parseOrderCSV(text:string):ParsedCSVRow[]{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(line=>line.trim()!=='');if(lines.length<2)throw new Error('CSV requires a header and at least one row');const headers=parseLine(lines[0]).map(value=>value.trim());const required=['externalRef','placedAt','orderType','itemCode','quantity'];for(const name of required)if(!headers.includes(name))throw new Error(`Missing column: ${name}`);return lines.slice(1).map((line,index)=>{const values=parseLine(line);const rawData=Object.fromEntries(headers.map((header,column)=>[header,values[column]??'']));return{id:createUuidV7(),rowNumber:index+2,externalRef:String(rawData.externalRef),placedAt:String(rawData.placedAt),orderType:String(rawData.orderType),itemCode:String(rawData.itemCode),quantity:Number(rawData.quantity),rawData}})}
export async function fileSHA256(text:string):Promise<string>{const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,'0')).join('')}
export async function importOrderCSV(api:string,tenantId:string,outletId:string,fileName:string,text:string):Promise<OrderImport>{const rows=parseOrderCSV(text);const fileSha256=await fileSHA256(text);return mutate<OrderImport>(api,'/order-imports',tenantId,outletId,{id:createUuidV7(),outletId,fileName,fileSha256,rows})}
export const fetchOrderImports=(api:string,tenantId:string,outletId:string)=>list<OrderImport>(api,'/order-imports',tenantId,outletId);
export const fetchPlanningRuns=(api:string,tenantId:string,outletId:string)=>list<PlanningRun>(api,'/planning-runs',tenantId,outletId);
export const generatePlanningRun=(api:string,tenantId:string,outletId:string)=>mutate<PlanningRun>(api,'/planning-runs',tenantId,outletId,{id:createUuidV7(),outletId});
export const planningApiBase=coreApiBase;
