import { createUuidV7, getDeviceId } from './kitchen';import { coreApiBase } from './coreInventory';
export interface Supplier{id:string;name:string;code:string;contactName:string;phone:string;active:boolean}
export interface POLine{id:string;ingredientId:string;ingredientName:string;unitId:string;unitSymbol:string;orderedQuantity:number;receivedQuantity:number;unitCostMinor:number}
export interface PurchaseOrder{id:string;supplierId:string;supplierName:string;poNumber:string;status:string;expectedAt?:string;currency:string;totalMinor:number;version:number;lines:POLine[]}
export interface TemperatureLog{id:string;location:string;temperatureC:number;safeMinC:number;safeMaxC:number;compliant:boolean;correctiveAction:string;measuredAt:string}
export interface ChecklistItem{id:string;label:string;required:boolean;completed:boolean}
export interface Checklist{id:string;checklistType:string;businessDate:string;status:string;version:number;items:ChecklistItem[]}
export interface StaffMember{id:string;employeeCode:string;displayName:string;role:string;active:boolean}
export interface StaffShift{id:string;staffMemberId:string;staffName:string;startsAt:string;endsAt:string;status:string;version:number}
export interface OpsTask{id:string;staffMemberId?:string;staffName?:string;title:string;dueAt?:string;priority:string;status:string;version:number}
function auth(tenant:string):{actorId:string;headers:Record<string,string>}{const token=sessionStorage.getItem('feastcloud.oidc-access-token');return token?{actorId:'manager-dashboard',headers:{Authorization:`Bearer ${token}`}}:{actorId:'manager-dashboard',headers:{'X-FeastCloud-Tenant-ID':tenant,'X-FeastCloud-Actor-ID':'manager-dashboard'}}}
async function mutate<T>(api:string,path:string,tenant:string,outlet:string,payload:Record<string,unknown>){const id=createUuidV7(),context=auth(tenant),envelope={id,tenantId:tenant,outletId:outlet,deviceId:getDeviceId(),actorId:context.actorId,occurredAt:new Date().toISOString(),source:'feastcloud.web',sourceId:id,schemaVersion:'1.0',idempotencyKey:id,payload};const response=await fetch(`${api}${path}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':id,...context.headers},body:JSON.stringify(envelope)});if(!response.ok)throw new Error(`${path}: ${response.status}`);const body=await response.json() as {data:T};return body.data}
async function list<T>(api:string,path:string,tenant:string,outlet?:string){const query=outlet?`?outletId=${encodeURIComponent(outlet)}`:'';const response=await fetch(`${api}${path}${query}`,{headers:{Accept:'application/json',...auth(tenant).headers},cache:'no-store'});if(!response.ok)throw new Error(`${path}: ${response.status}`);const body=await response.json() as {data:T[]};return body.data}
export const dailyOpsApiBase=coreApiBase;
export const fetchSuppliers=(a:string,t:string)=>list<Supplier>(a,'/suppliers',t);export const createSupplier=(a:string,t:string,o:string,name:string,code:string)=>mutate<Supplier>(a,'/suppliers',t,o,{id:createUuidV7(),name,code});
export const fetchPOs=(a:string,t:string,o:string)=>list<PurchaseOrder>(a,'/purchase-orders',t,o);export const createPO=(a:string,t:string,o:string,input:{supplierId:string;poNumber:string;ingredientId:string;unitId:string;quantity:number;unitCostMinor:number})=>mutate<PurchaseOrder>(a,'/purchase-orders',t,o,{id:createUuidV7(),outletId:o,supplierId:input.supplierId,poNumber:input.poNumber,lines:[{id:createUuidV7(),ingredientId:input.ingredientId,unitId:input.unitId,orderedQuantity:input.quantity,unitCostMinor:input.unitCostMinor}]});export const transitionPO=(a:string,t:string,o:string,v:PurchaseOrder,status:string)=>mutate<PurchaseOrder>(a,`/purchase-orders/${v.id}/transitions`,t,o,{status,expectedVersion:v.version});export const receivePO=(a:string,t:string,o:string,v:PurchaseOrder)=>mutate<PurchaseOrder>(a,'/goods-receipts',t,o,{id:createUuidV7(),outletId:o,purchaseOrderId:v.id,expectedVersion:v.version,lines:v.lines.filter(x=>x.receivedQuantity<x.orderedQuantity).map(x=>({id:createUuidV7(),purchaseOrderLineId:x.id,ingredientId:x.ingredientId,unitId:x.unitId,quantity:x.orderedQuantity-x.receivedQuantity,lotCode:`PO-${v.poNumber}`}))});
export const fetchTemperatures=(a:string,t:string,o:string)=>list<TemperatureLog>(a,'/temperature-logs',t,o);export const recordTemperature=(a:string,t:string,o:string,input:{location:string;temperatureC:number;safeMinC:number;safeMaxC:number;correctiveAction:string})=>mutate<TemperatureLog>(a,'/temperature-logs',t,o,{id:createUuidV7(),outletId:o,...input,measuredAt:new Date().toISOString()});
export const fetchChecklists=(a:string,t:string,o:string)=>list<Checklist>(a,'/checklists',t,o);export const createChecklist=(a:string,t:string,o:string,type:string)=>mutate<Checklist>(a,'/checklists',t,o,{id:createUuidV7(),outletId:o,checklistType:type,businessDate:new Date().toISOString().slice(0,10),items:(type==='opening'?['Sanitize preparation surfaces','Verify cold storage temperatures','Confirm stations are stocked']:['Clean and close stations','Record waste and final stock','Secure gas and electrical equipment']).map(label=>({id:createUuidV7(),label,required:true}))});export const completeChecklistItem=(a:string,t:string,o:string,v:Checklist,item:ChecklistItem)=>mutate<Checklist>(a,`/checklists/${v.id}/items/${item.id}/complete`,t,o,{expectedVersion:v.version});
export const fetchStaff=(a:string,t:string)=>list<StaffMember>(a,'/staff-members',t);export const createStaff=(a:string,t:string,o:string,name:string,role:string)=>mutate<StaffMember>(a,'/staff-members',t,o,{id:createUuidV7(),employeeCode:`EMP-${Date.now().toString().slice(-6)}`,displayName:name,role});
export const fetchShifts=(a:string,t:string,o:string)=>list<StaffShift>(a,'/shifts',t,o);export const createShift=(a:string,t:string,o:string,staffId:string)=>{const start=new Date(),end=new Date(start.getTime()+8*3600000);return mutate<StaffShift>(a,'/shifts',t,o,{id:createUuidV7(),outletId:o,staffMemberId:staffId,startsAt:start.toISOString(),endsAt:end.toISOString()})};export const transitionShift=(a:string,t:string,o:string,v:StaffShift,status:string)=>mutate<StaffShift>(a,`/shifts/${v.id}/transitions`,t,o,{status,expectedVersion:v.version});
export const fetchTasks=(a:string,t:string,o:string)=>list<OpsTask>(a,'/tasks',t,o);export const createTask=(a:string,t:string,o:string,title:string,staffId:string)=>mutate<OpsTask>(a,'/tasks',t,o,{id:createUuidV7(),outletId:o,staffMemberId:staffId||undefined,title,priority:'normal'});export const transitionTask=(a:string,t:string,o:string,v:OpsTask,status:string)=>mutate<OpsTask>(a,`/tasks/${v.id}/transitions`,t,o,{status,expectedVersion:v.version});
