import { createUuidV7, getDeviceId } from './kitchen';
import { coreApiBase } from './coreInventory';

export interface ConfigurationSnapshot { id:string; sequence:number; contentSha256:string; signature:string; publicKey:string; algorithm:string; status:string; signedAt:string }
export interface EdgeCheckpoint { edgeId:string; lastOperationId?:string; lastReceivedAt?:string; lastAcceptedAt?:string; backlogCount:number; degraded:boolean; lastProblemCode?:string; version:number; updatedAt:string }
export interface ReconciliationCase { id:string; sourceType:string; category:string; severity:string; status:'open'|'in_progress'|'resolved'|'dismissed'; title:string; assignedTo?:string; resolution?:string; version:number; openedAt:string; updatedAt:string }
export interface OperationalIncident { id:string; incidentType:string; severity:string; status:'open'|'monitoring'|'resolved'; title:string; version:number; startedAt:string; updatedAt:string }
export interface BackupManifest { id:string; backupType:string; storageReference:string; contentSha256:string; sizeBytes:number; encrypted:boolean; verified:boolean; completedAt:string; recoveryPointAt:string }
export interface RestoreDrill { id:string; backupManifestId:string; status:'passed'|'failed'; targetEnvironment:string; recoveryTimeSeconds:number; integrityVerified:boolean; recordedAt:string }
export interface BackupEvidence { backups:BackupManifest[]; restoreDrills:RestoreDrill[] }

function auth(tenantId:string):{actorId:string;headers:Record<string,string>}{const token=sessionStorage.getItem('feastcloud.oidc-access-token');if(token)return{actorId:'manager-dashboard',headers:{Authorization:`Bearer ${token}`}};return{actorId:'manager-dashboard',headers:{'X-FeastCloud-Tenant-ID':tenantId,'X-FeastCloud-Actor-ID':'manager-dashboard'}}}
async function mutation<T>(api:string,path:string,tenantId:string,outletId:string,payload:Record<string,unknown>):Promise<T>{const id=createUuidV7();const context=auth(tenantId);const envelope={id,tenantId,outletId,deviceId:getDeviceId(),actorId:context.actorId,occurredAt:new Date().toISOString(),source:'feastcloud.web',sourceId:id,schemaVersion:'1.0',idempotencyKey:id,payload};const response=await fetch(`${api}${path}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':id,...context.headers},body:JSON.stringify(envelope)});if(!response.ok)throw new Error(`${path} returned ${response.status}`);const body=await response.json() as {data?:T};if(!body.data)throw new Error('Response is invalid');return body.data}
async function read<T>(api:string,path:string,tenantId:string,outletId?:string):Promise<T>{const separator=path.includes('?')?'&':'?';const url=outletId?`${api}${path}${separator}outletId=${encodeURIComponent(outletId)}&limit=50`:`${api}${path}`;const response=await fetch(url,{headers:{Accept:'application/json',...auth(tenantId).headers},cache:'no-store'});if(!response.ok)throw new Error(`${path} returned ${response.status}`);const body=await response.json() as {data?:T};if(body.data===undefined)throw new Error('Response is invalid');return body.data}

export const operationsApiBase=coreApiBase;
export const fetchSnapshots=(api:string,tenant:string,outlet:string)=>read<ConfigurationSnapshot[]>(api,'/configuration-snapshots',tenant,outlet);
export const publishSnapshot=(api:string,tenant:string,outlet:string,content:Record<string,unknown>)=>mutation<ConfigurationSnapshot>(api,'/configuration-snapshots',tenant,outlet,{id:createUuidV7(),outletId:outlet,content});
export const fetchCheckpoints=(api:string,tenant:string,outlet:string)=>read<EdgeCheckpoint[]>(api,'/edge-checkpoints',tenant,outlet);
export const fetchCases=(api:string,tenant:string,outlet:string)=>read<ReconciliationCase[]>(api,'/reconciliation-cases',tenant,outlet);
export const actOnCase=(api:string,tenant:string,outlet:string,value:ReconciliationCase,action:'retry'|'resolve'|'dismiss'|'reopen')=>mutation<ReconciliationCase>(api,`/reconciliation-cases/${value.id}/actions`,tenant,outlet,{action,expectedVersion:value.version,notes:action==='resolve'?'Reviewed by manager':''});
export const fetchIncidents=(api:string,tenant:string,outlet:string)=>read<OperationalIncident[]>(api,'/incidents',tenant,outlet);
export const createIncident=(api:string,tenant:string,outlet:string,title:string,severity:string)=>mutation<OperationalIncident>(api,'/incidents',tenant,outlet,{id:createUuidV7(),outletId:outlet,incidentType:'operations',severity,title,details:{reportedFrom:'manager-dashboard'}});
export const transitionIncident=(api:string,tenant:string,outlet:string,value:OperationalIncident,status:'monitoring'|'resolved'|'open')=>mutation<OperationalIncident>(api,`/incidents/${value.id}/actions`,tenant,outlet,{status,expectedVersion:value.version,message:`Manager changed incident to ${status}`});
export const fetchBackupEvidence=(api:string,tenant:string)=>read<BackupEvidence>(api,'/backup-evidence',tenant);
export const recordBackup=(api:string,tenant:string,outlet:string,reference:string,contentSha256:string,sizeBytes:number)=>{const now=new Date().toISOString();return mutation<BackupManifest>(api,'/backup-evidence',tenant,outlet,{id:createUuidV7(),outletId:outlet,backupType:'edge',storageReference:reference,contentSha256,sizeBytes,encrypted:true,verified:true,startedAt:now,completedAt:now,recoveryPointAt:now})};
export const recordRestoreDrill=(api:string,tenant:string,outlet:string,backup:BackupManifest)=>{const now=new Date().toISOString();return mutation<RestoreDrill>(api,'/restore-drills',tenant,outlet,{id:createUuidV7(),backupManifestId:backup.id,status:'passed',targetEnvironment:'isolated-validation',startedAt:now,completedAt:now,recoveryTimeSeconds:0,integrityVerified:true,notes:'Manager-recorded verification'})};
