import{createUuidV7,getDeviceId}from'./kitchen';import{coreApiBase}from'./coreInventory';
export interface Guest{id:string;fullName:string;phone:string;email:string;locale:string;dietaryLabels:string[];marketingConsent:boolean;version:number}
export interface Reservation{id:string;guestId?:string;guestName:string;phone:string;partySize:number;scheduledFor:string;durationMinutes:number;status:string;version:number}
export interface Promotion{id:string;code:string;name:string;discountType:'percentage'|'fixed';discountValue:number;minOrderMinor:number;startsAt:string;endsAt:string;redemptionCount:number;active:boolean;version:number}
export interface LoyaltyAccount{id:string;guestId:string;guestName:string;pointsBalance:number;lifetimeEarned:number;version:number}
export interface Tender{id:string;orderId:string;cashShiftId?:string;tenderType:string;amountMinor:number;currency:string;status:string;reversesTenderId?:string;occurredAt:string}
function auth(t:string):{actorId:string;headers:Record<string,string>}{const token=sessionStorage.getItem('feastcloud.oidc-access-token');return token?{actorId:'manager',headers:{Authorization:`Bearer ${token}`}}:{actorId:'manager',headers:{'X-FeastCloud-Tenant-ID':t,'X-FeastCloud-Actor-ID':'manager'}}}
async function mutate<T>(a:string,p:string,t:string,o:string,payload:Record<string,unknown>){const id=createUuidV7(),c=auth(t),body={id,tenantId:t,outletId:o,deviceId:getDeviceId(),actorId:c.actorId,occurredAt:new Date().toISOString(),source:'feastcloud.web',sourceId:id,schemaVersion:'1.0',idempotencyKey:id,payload};const r=await fetch(a+p,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':id,...c.headers},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${p}: ${r.status}`);return(await r.json()as{data:T}).data}
async function list<T>(a:string,p:string,t:string,o?:string){const q=o?`?outletId=${encodeURIComponent(o)}&limit=200`:'?limit=200';const r=await fetch(a+p+q,{headers:{Accept:'application/json',...auth(t).headers},cache:'no-store'});if(!r.ok)throw new Error(`${p}: ${r.status}`);return(await r.json()as{data:T[]}).data}
export const guestGrowthApiBase=coreApiBase;
export const fetchGuests=(a:string,t:string)=>list<Guest>(a,'/guests',t);export const createGuest=(a:string,t:string,o:string,v:{fullName:string;phone:string;marketingConsent:boolean})=>mutate<Guest>(a,'/guests',t,o,{id:createUuidV7(),...v,email:'',locale:'en-IN',dietaryLabels:[],notes:''});export const setConsent=(a:string,t:string,o:string,v:Guest)=>mutate<Guest>(a,`/guests/${v.id}/consent`,t,o,{granted:!v.marketingConsent,expectedVersion:v.version,source:'manager_workspace'});
export const fetchReservations=(a:string,t:string,o:string)=>list<Reservation>(a,'/reservations',t,o);export const createReservation=(a:string,t:string,o:string,v:{guestId?:string;guestName:string;phone:string;partySize:number;scheduledFor:string;status:string})=>mutate<Reservation>(a,'/reservations',t,o,{id:createUuidV7(),outletId:o,...v,durationMinutes:90,source:'staff',notes:''});export const transitionReservation=(a:string,t:string,o:string,v:Reservation,status:string)=>mutate<Reservation>(a,`/reservations/${v.id}/transitions`,t,o,{status,expectedVersion:v.version});
export const fetchPromotions=(a:string,t:string,o:string)=>list<Promotion>(a,'/promotions',t,o);export const createPromotion=(a:string,t:string,o:string,v:{code:string;name:string;discountType:string;discountValue:number;minOrderMinor:number})=>mutate<Promotion>(a,'/promotions',t,o,{id:createUuidV7(),outletId:o,...v,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+30*86400000).toISOString(),redemptionLimit:null});export const redeemPromotion=(a:string,t:string,o:string,code:string,basketMinor:number,guestId='')=>mutate<{discountMinor:number}>(a,'/promotions/redeem',t,o,{id:createUuidV7(),code,basketMinor,guestId,orderId:''});
export const fetchLoyalty=(a:string,t:string)=>list<LoyaltyAccount>(a,'/loyalty-accounts',t);export const adjustLoyalty=(a:string,t:string,o:string,v:LoyaltyAccount,delta:number)=>mutate<LoyaltyAccount>(a,`/loyalty-accounts/${v.id}/events`,t,o,{id:createUuidV7(),eventType:delta>0?'earn':'redeem',pointsDelta:delta,reason:delta>0?'Manager award':'Guest redemption',orderId:'',expectedVersion:v.version});
export const fetchTenders=(a:string,t:string,o:string)=>list<Tender>(a,'/tenders',t,o);export const reverseTender=(a:string,t:string,o:string,v:Tender,amountMinor:number,cashShiftId='')=>mutate<Tender>(a,`/tenders/${v.id}/reverse`,t,o,{id:createUuidV7(),amountMinor,cashShiftId,providerReference:'manager_refund'});
